config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users
  resources :sessions

  resources :posts do
    resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments , dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
    
  attr_accessor :password_hash
  before_save :encrypt_password
  
  validates_confirmation_of :password_hash
  validates_presence_of :password_hash, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
    
  def self.authenticate(email, password_hash)
    user = find_by_email(email)
    if user && user.password_hash == Digest::MD5.digest(password_hash)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    self.password_hash = Digest::MD5.digest(password_hash)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	helper_method :current_user

  def new
    var = klass.to_s.downcase
    instance_variable_set "@#{var}", klass.new
  end

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def klass
  Comment
end

def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@post = Post.all 
  end

  def klass
    Post
  end

  def create
	 @post = Post.new(params[:posts].permit(:title, :body))
	 if @post.save
    redirect_to @post
   else
    render 'new'
   end
	end

  def show
    @post = Post.find params[:id]
  end
  
  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id] 
    @post.update(post_params)
    redirect_to post_url(@post)
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

def create
  user = User.authenticate(params[:email], params[:password_hash])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

private
  def user_params
    params.require(:user).permit(:email, :password_hash)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= link_to 'New post', new_post_path %>
<br>
<% @post.each do |post|%>
<%=post.id%>-
<%=post.title%>
<%=post.body%>
<%=link_to 'show',post_path(post.id)%>
<%= link_to 'Edit', edit_post_path(post.id) %>
<%= link_to 'Destroy', post_path(post),method: :delete, data: { confirm: 'desea eliminar?' } %>
<br>
<%end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<%= form_for  @post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Atras', posts_path %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<h1>
<%= @post.title%>	
<br>
<%= @post.body%>
</h1>

<h2>Comentario</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Comentario de:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <%= comment.body %>
  </p>
<% end %>

<h2>Agregar Comentario:</h2>
<%= form_for([@post, @post.comments.build]) do |f|%>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Atras', posts_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password_hash %><br />
    <%= f.password_field :password_hash %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>